### ISSUE TITLE
"In den Warenkorb" button still deactivated after selection of article variant 

### ISSUE THREAD

**Issue by hiro-git-hub** [8mylez/EmzBiancoTheme#56]
Thank you for fixing the issue with variant articles. The "In den Warenkorb" button is still deactivated, after selection of an article variant: 
![bildschirmfoto vom 2019-01-18 08-19-41](https://user-images.githubusercontent.com/22772200/51371222-d7ba4b00-1af9-11e9-9760-bdccb00ce2fc.png)

**Comment by subzer047** [comment]
this is fixed with 1.3.0
