### ISSUE TITLE
Our Plugin "Zwei Bilder ein Text" was removed with the Merge#20

### ISSUE THREAD

**Issue by PrinceNG** [8mylez/EmzBiancoTheme#66]
With the faulty #20 merge you put the Hover Classic and Premium in,
but also delete the "Zwei Bilder ein Text" plugin.

Is there a reason for removing the plugin?
Thinking it's a nice content element...

Would be nice if the theme in the base works again.
There are still some who are going through the workshop.

**Comment by eemzet** [comment]
Hey PrinceNG,

thank you for your feedback. I will check that out and see if we can get the emotion elements "Zwei Bilder ein Text" back again.

Best,
Alexander

**Comment by eemzet** [comment]
Hey PrinceNG,

the emotion element was removed, because we merged the other emotion elements into the theme. So it was replaced.

If you still want the old emotion element, you can extract it from the commits yourself and copy it from the old code.

Best,
Alexander
